# Generated by Django 4.0.3 on 2022-03-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('expertype', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('pic_name', models.FileField(default='', max_length=255, upload_to='healthapp/campaign_pic')),
            ],
        ),
    ]
