# Generated by Django 4.0.3 on 2022-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthexperts',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
