# Generated by Django 4.0.3 on 2022-03-10 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_alter_healthexperts_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
