# Generated by Django 4.0.3 on 2022-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0008_alter_healthexperts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthexperts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='healthexperts',
            name='user_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
