# Generated by Django 4.0.3 on 2022-03-25 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_remove_healthexperts_id_remove_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.patient'),
        ),
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user1_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.patient')),
                ('user2_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.healthexperts')),
            ],
        ),
    ]
