# Generated by Django 4.0.3 on 2022-04-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0013_expert_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert_detail',
            old_name='highest_qualification',
            new_name='qualification',
        ),
    ]
