# Generated by Django 4.0.3 on 2022-04-12 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0014_rename_highest_qualification_expert_detail_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_Date', models.DateField(default=django.utils.timezone.now, verbose_name='start_date')),
                ('to_Date', models.DateField(default=django.utils.timezone.now, verbose_name='end_date')),
                ('expert_user_name', models.CharField(default='abc', max_length=45)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='not_comfirm', max_length=50)),
                ('response_text', models.CharField(default=' ', max_length=50)),
                ('user_message_text', models.CharField(default=' ', max_length=45)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.patient')),
            ],
        ),
    ]
