# Generated by Django 4.0.3 on 2022-04-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0015_booking_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_request',
            name='response_text',
            field=models.CharField(default='No response', max_length=50),
        ),
    ]
