# Generated by Django 4.0.3 on 2022-04-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0016_alter_booking_request_response_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feed_back',
        ),
    ]
