# Generated by Django 4.0.3 on 2022-04-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0017_rename_feedback_feed_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_back',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.patient'),
        ),
    ]
